$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$failures = [System.Collections.Generic.List[string]]::new()
$remoteCssResourcePattern = '(?i)(?:https?:)?//'

function Assert-File([string]$relativePath) {
    if (-not (Test-Path -LiteralPath (Join-Path $projectRoot $relativePath) -PathType Leaf)) {
        $failures.Add("Missing file: $relativePath")
    }
}

function Assert-Match([string]$relativePath, [string]$pattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }
    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if ($content -notmatch $pattern) { $failures.Add("$relativePath lacks $label") }
}

function Assert-NoMatch([string]$relativePath, [string]$pattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }
    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if ($content -match $pattern) { $failures.Add("$relativePath contains prohibited $label") }
}

function Get-NormalizedText([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    return ((Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n").TrimEnd() + "`n"
}

function Get-ExpectedStandaloneTheme([string]$palettePath) {
    $header = "/* Generated by scripts/build.ps1. Edit src/*.css, then rebuild. */`n`n"
    return $header + (Get-NormalizedText $palettePath) + "`n" + (Get-NormalizedText 'src/base.css')
}

function Assert-CanonicalUtf8([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    $bytes = [System.IO.File]::ReadAllBytes($path)
    if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        $failures.Add("$relativePath contains a UTF-8 BOM")
    }

    try {
        $strictUtf8 = [System.Text.UTF8Encoding]::new($false, $true)
        $text = $strictUtf8.GetString($bytes)
    } catch {
        $failures.Add("$relativePath is not valid UTF-8")
        return
    }

    if ($text.Contains("`r")) {
        $failures.Add("$relativePath does not use canonical LF line endings")
    }
    if (-not $text.EndsWith("`n")) {
        $failures.Add("$relativePath lacks its final LF")
    }
}

function Get-ByteHash([byte[]]$bytes) {
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        return [System.BitConverter]::ToString($sha256.ComputeHash($bytes))
    } finally {
        $sha256.Dispose()
    }
}

function Assert-DeterministicBuilder {
    $releasePaths = @('tangentzx-light.css', 'tangentzx-dark.css')
    $originalBytes = @{}
    $originalHashes = @{}

    foreach ($relativePath in $releasePaths) {
        $path = Join-Path $projectRoot $relativePath
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            $failures.Add("Cannot snapshot missing build output: $relativePath")
            return
        }
        $originalBytes[$relativePath] = [System.IO.File]::ReadAllBytes($path)
        $originalHashes[$relativePath] = Get-ByteHash $originalBytes[$relativePath]
    }

    $buildSucceeded = $false
    $outputsIdentical = $true
    try {
        & (Join-Path $projectRoot 'scripts/build.ps1')
        $buildSucceeded = $true

        foreach ($relativePath in $releasePaths) {
            $path = Join-Path $projectRoot $relativePath
            if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
                $failures.Add("scripts/build.ps1 removed build output: $relativePath")
                $outputsIdentical = $false
                continue
            }
            $rebuiltHash = Get-ByteHash ([System.IO.File]::ReadAllBytes($path))
            if ($rebuiltHash -cne $originalHashes[$relativePath]) {
                $failures.Add("scripts/build.ps1 changed unchanged-source output bytes: $relativePath")
                $outputsIdentical = $false
            }
        }
    } catch {
        $failures.Add("scripts/build.ps1 execution failed: $($_.Exception.Message)")
    } finally {
        foreach ($relativePath in $releasePaths) {
            $path = Join-Path $projectRoot $relativePath
            $currentHash = if (Test-Path -LiteralPath $path -PathType Leaf) {
                Get-ByteHash ([System.IO.File]::ReadAllBytes($path))
            } else {
                $null
            }
            if ($currentHash -cne $originalHashes[$relativePath]) {
                [System.IO.File]::WriteAllBytes($path, $originalBytes[$relativePath])
            }
        }
    }

    if ($buildSucceeded -and $outputsIdentical) {
        Write-Output 'Deterministic build execution passed.'
    }
}

function Assert-RuleMatch([string]$relativePath, [string]$selectorPattern, [string]$declarationPattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $matchingRules = @(Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $selectorPattern })
    if ($matchingRules.Count -eq 0 -or -not ($matchingRules | Where-Object { $_.Body -match $declarationPattern })) {
        $failures.Add("$relativePath lacks $label in its $selectorPattern rule")
    }
}

function Assert-RuleNoMatch([string]$relativePath, [string]$selectorPattern, [string]$declarationPattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $matchingRules = @(Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $selectorPattern })
    if ($matchingRules | Where-Object { $_.Body -match $declarationPattern }) {
        $failures.Add("$relativePath contains prohibited $label in its $selectorPattern rule")
    }
}

function Assert-NoBarePreCardRule([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    foreach ($rule in (Get-CssRuleBlocks $content)) {
        $hasBarePreSelector = @($rule.Selector -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -match '^#write\s+pre$' }).Count -gt 0
        $hasCardDeclaration = $rule.Body -match '(?i)\b(?:padding|border|border-radius|background|box-shadow)\s*:'
        if ($hasBarePreSelector -and $hasCardDeclaration) {
            $failures.Add("$relativePath applies code-card declarations to bare #write pre")
            return
        }
    }
}

function Assert-NoBareSelector([string]$relativePath, [string]$selector, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    foreach ($rule in (Get-CssRuleBlocks $content)) {
        if (@($rule.Selector -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -eq $selector }).Count -gt 0) {
            $failures.Add("$relativePath contains prohibited bare $label selector")
            return
        }
    }
}

function Test-HasForbiddenTyporaCodeSelector([string]$content) {
    foreach ($rule in (Get-CssRuleBlocks $content)) {
        $hasVisualDeclaration = $rule.Body -match '(?i)\b(?:font(?:-family)?|padding(?:-[a-z]+)?|border(?:-[a-z]+)?|border-radius|background(?:-[a-z]+)?|box-shadow|overflow(?:-[a-z]+)?|color)\s*:'
        $hasCodeMirrorLineBoxDeclaration = $rule.Body -match '(?i)\b(?:padding(?:-[a-z]+)?|border(?:-[a-z]+)?|border-radius|background(?:-[a-z]+)?|box-shadow)\s*:'
        foreach ($selector in ($rule.Selector -split ',' | ForEach-Object { $_.Trim() })) {
            $isCodeMirrorLine = $selector -match '(?i)\.CodeMirror-line\b'
            $isWhitelistedMetaPre = $selector -eq '#write pre.md-meta-block'
            $isWritePreDescendant = -not $isWhitelistedMetaPre -and $selector -match '(?i)^#write\b.*(?:\s|[>+~])pre(?:\b|[.:#\[])'
            if (($isCodeMirrorLine -and $hasCodeMirrorLineBoxDeclaration) -or ($isWritePreDescendant -and $hasVisualDeclaration)) {
                return $true
            }
        }
    }
    return $false
}

function Test-HasForbiddenCodeMirrorDeclaration([string]$content) {
    foreach ($rule in (Get-CssRuleBlocks $content)) {
        foreach ($selector in ($rule.Selector -split ',' | ForEach-Object { $_.Trim() })) {
            $isCodeMirrorRule = $selector -match '(?i)(?:\.CodeMirror\b|\.cm-s-(?:inner|typora-default)\b)'
            if (-not $isCodeMirrorRule) { continue }

            $allowsBackground = $selector -match '(?i)(?:\.cm-s-(?:inner|typora-default)|\.CodeMirror-(?:selected|activeline-background|gutters))\s*$'
            $isCursor = $selector -match '(?i)\.CodeMirror-cursor\s*$'
            foreach ($declaration in ([regex]::Matches($rule.Body, '(?im)([a-z-]+)\s*:'))) {
                $property = $declaration.Groups[1].Value.ToLowerInvariant()
                if ($property -in @('color', 'font-family')) { continue }
                if ($property -in @('background', 'background-color') -and $allowsBackground) { continue }
                if ($property -eq 'border-left-color' -and $isCursor) { continue }
                return $true
            }
        }
    }
    return $false
}

function Assert-NoForbiddenCodeMirrorDeclaration([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if (Test-HasForbiddenCodeMirrorDeclaration $content) {
        $failures.Add("$relativePath contains a forbidden CodeMirror declaration")
    }
}

function Assert-NoForbiddenTyporaCodeSelector([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if (Test-HasForbiddenTyporaCodeSelector $content) {
        $failures.Add("$relativePath contains a forbidden Typora code-line selector")
    }
}

function Assert-MediaRuleMatch([string]$relativePath, [string]$mediaSelector, [string]$selector, [string]$declarationPattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $mediaRules = @(Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $mediaSelector })
    $matchingRules = @($mediaRules | ForEach-Object { Get-CssRuleBlocks $_.Body } | Where-Object {
        @($_.Selector -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -eq $selector }).Count -gt 0 -and $_.Body -match $declarationPattern
    })
    if ($matchingRules.Count -eq 0) {
        $failures.Add("$relativePath lacks $label in its $selector rule within $mediaSelector")
    }
}

function Assert-MediaNoBareSelector([string]$relativePath, [string]$mediaSelector, [string]$selector, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    foreach ($mediaRule in (Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $mediaSelector })) {
        foreach ($rule in (Get-CssRuleBlocks $mediaRule.Body)) {
            if (@($rule.Selector -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -eq $selector }).Count -gt 0) {
                $failures.Add("$relativePath contains prohibited $label selector within $mediaSelector")
                return
            }
        }
    }
}

function Assert-MediaRuleNoMatch([string]$relativePath, [string]$mediaSelector, [string]$selector, [string]$declarationPattern, [string]$label) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    foreach ($mediaRule in (Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $mediaSelector })) {
        foreach ($rule in (Get-CssRuleBlocks $mediaRule.Body)) {
            $hasSelector = @($rule.Selector -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -eq $selector }).Count -gt 0
            if ($hasSelector -and $rule.Body -match $declarationPattern) {
                $failures.Add("$relativePath contains prohibited $label in its $selector rule within $mediaSelector")
                return
            }
        }
    }
}

function Assert-MediaNoPaletteDeclarations([string]$relativePath, [string]$mediaSelector) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $palettePropertyPattern = '(?im)(?:^|[;\r\n])\s*(?:color|background(?:-color)?|border(?:-(?:top|right|bottom|left))?(?:-color)?|fill|stroke)\s*:'
    foreach ($mediaRule in (Get-CssRuleBlocks $content | Where-Object { $_.Depth -eq 0 -and $_.Selector -match $mediaSelector })) {
        foreach ($rule in (Get-CssRuleBlocks $mediaRule.Body)) {
            if ($rule.Body -match $palettePropertyPattern) {
                $failures.Add("$relativePath contains a print-only palette declaration in $($rule.Selector)")
            }
        }
    }
}

function Get-CssRuleBlocks([string]$content) {
    $blocks = [System.Collections.Generic.List[object]]::new()
    $stack = [System.Collections.Generic.Stack[object]]::new()
    $segmentStart = 0

    for ($index = 0; $index -lt $content.Length; $index++) {
        if ($content[$index] -eq '{') {
            $stack.Push([pscustomobject]@{
                Selector = $content.Substring($segmentStart, $index - $segmentStart).Trim()
                BodyStart = $index + 1
                Depth = $stack.Count
            })
            $segmentStart = $index + 1
            continue
        }
        if ($content[$index] -eq '}' -and $stack.Count -gt 0) {
            $rule = $stack.Pop()
            $blocks.Add([pscustomobject]@{
                Selector = $rule.Selector
                Body = $content.Substring($rule.BodyStart, $index - $rule.BodyStart)
                Depth = $rule.Depth
            })
            $segmentStart = $index + 1
        }
    }

    return $blocks
}

function Get-GitTrackedFiles([string]$repository, [string]$pattern) {
    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $files = @(git -C $repository ls-files -- $pattern 2>$null)
        $succeeded = $LASTEXITCODE -eq 0
    } finally {
        $ErrorActionPreference = $previousErrorActionPreference
    }
    [pscustomobject]@{
        Succeeded = $succeeded
        Files = $files
    }
}

function Test-FixedRightSidebarRule([string]$content) {
    foreach ($rule in (Get-CssRuleBlocks $content)) {
        $isNavigationRule = $rule.Selector -match '(?i)(sidebar|outline|toc|file-library|file-panel|file-tree|nav-panel)'
        $isFixed = $rule.Body -match '(?i)\bposition\s*:\s*fixed\b'
        $isRightAnchored = $rule.Body -match '(?i)(?:\bright\s*:|\binset-inline-end\s*:)'
        if ($isNavigationRule -and $isFixed -and $isRightAnchored) {
            return $true
        }
    }
    return $false
}

function Get-OutsideFencedMarkdown([string]$content) {
    $outside = [System.Collections.Generic.List[string]]::new()
    $fence = $null
    $fenceCounts = @{ cpp = 0; text = 0; mermaid = 0 }

    foreach ($line in ($content -split "`n", -1)) {
        if ($null -ne $fence) {
            if ($line -match '^```\s*$') {
                $fence = $null
            }
            continue
        }

        if ($line -match '^```(cpp|text|mermaid)\s*$') {
            $fence = $Matches[1]
            $fenceCounts[$fence]++
            continue
        }
        if ($line -match '^```') {
            throw "showcase.md has an unsupported fenced-code opener: $line"
        }
        if ($line -match '^```\s*$') {
            throw 'showcase.md has a fenced-code closer without an opener'
        }
        $outside.Add($line)
    }

    if ($null -ne $fence) {
        throw "showcase.md has an unclosed $fence fence"
    }

    [pscustomobject]@{
        Outside = $outside -join "`n"
        FenceCounts = $fenceCounts
    }
}

function Get-ShowcaseMarkdown([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Cannot inspect missing file: $relativePath")
        return $null
    }

    $content = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $analysis = Get-OutsideFencedMarkdown $content
    [pscustomobject]@{
        Content = $content
        Outside = $analysis.Outside
        FenceCounts = $analysis.FenceCounts
    }
}

function Assert-ShowcaseMatch([string]$content, [string]$pattern, [string]$label) {
    if ($content -notmatch $pattern) { $failures.Add("showcase.md lacks $label") }
}

@('.gitattributes', 'src/base.css', 'src/light.css', 'src/dark.css', 'scripts/build.ps1',
  'tangentzx-light.css', 'tangentzx-dark.css', 'README.md', 'showcase.md',
  'screenshots/README.md') |
    ForEach-Object { Assert-File $_ }

$prohibitedPublicationPaths = @(git -C $projectRoot ls-files -- 'docs/superpowers' 'demo.md' 'assets/demo-placeholder.svg')
if ($LASTEXITCODE -ne 0) {
    $failures.Add('Unable to inspect tracked publication paths')
} elseif ($prohibitedPublicationPaths.Count -gt 0) {
    $failures.Add("Public repository tracks internal or legacy paths: $($prohibitedPublicationPaths -join ', ')")
}

Assert-Match '.gitattributes' '(?m)^\*\.css\s+text\s+eol=lf\s*$' 'LF-only CSS Git attribute'

foreach ($entry in @('src/light.css', 'src/dark.css')) {
    foreach ($token in @('bg','surface','surface-raised','text','text-muted','primary','accent','nav-accent','nav-hover','border','code-bg','code-text','selection','shadow','gradient')) {
        Assert-Match $entry "--tzx-$token\s*:" "--tzx-$token token"
    }
}
foreach ($entry in @('src/light.css', 'src/dark.css', 'src/base.css', 'tangentzx-light.css', 'tangentzx-dark.css')) {
    Assert-NoMatch $entry $remoteCssResourcePattern 'remote URL'
    Assert-NoMatch $entry '@font-face' 'bundled font'
}

foreach ($mapping in @{
    '--bg-color' = 'var\(--tzx-bg\)'
    '--text-color' = 'var\(--tzx-text\)'
    '--md-char-color' = 'var\(--tzx-text-muted\)'
    '--meta-content-color' = 'var\(--tzx-text-muted\)'
    '--primary-color' = 'var\(--tzx-primary\)'
    '--primary-btn-border-color' = 'var\(--tzx-primary\)'
    '--primary-btn-text-color' = 'var\(--tzx-bg\)'
    '--window-border' = '1px\s+solid\s+var\(--tzx-border\)'
    '--active-file-bg-color' = 'var\(--tzx-nav-hover\)'
    '--active-file-text-color' = 'var\(--tzx-nav-accent\)'
    '--active-file-border-color' = 'var\(--tzx-nav-accent\)'
    '--side-bar-bg-color' = 'var\(--tzx-surface\)'
    '--item-hover-bg-color' = 'var\(--tzx-nav-hover\)'
    '--item-hover-text-color' = 'var\(--tzx-text\)'
    '--monospace' = 'var\(--tzx-code-font\)'
}.GetEnumerator()) {
    Assert-RuleMatch 'src/base.css' '^:root$' (([regex]::Escape($mapping.Key)) + '\s*:\s*' + $mapping.Value) "native $($mapping.Key) mapping"
}

Assert-Match 'src/light.css' '#4051b5' 'light primary color'
Assert-Match 'src/light.css' '#526cfe' 'light accent color'
Assert-Match 'src/light.css' '--tzx-nav-accent\s*:\s*#6171f5' 'light navigation accent color'
Assert-Match 'src/dark.css' '--tzx-nav-accent\s*:\s*#7dafe9' 'dark navigation accent color'
Assert-Match 'src/light.css' '--tzx-nav-hover\s*:\s*rgba\(63,\s*81,\s*181,\s*0\.08\)' 'light navigation hover color'
Assert-Match 'src/dark.css' '--tzx-nav-hover\s*:\s*rgba\(97,\s*175,\s*239,\s*0\.08\)' 'dark navigation hover color'
Assert-Match 'src/dark.css' '--tzx-bg\s*:\s*#282c34' 'blog dark page background'
Assert-Match 'src/dark.css' '--tzx-surface\s*:\s*rgba\(33,\s*37,\s*43,\s*0\.76\)' 'blog dark content surface'
Assert-Match 'src/dark.css' '--tzx-text\s*:\s*#abb2bf' 'blog dark prose color'
Assert-Match 'src/base.css' 'max-width\s*:\s*880px' '880px article width'

Assert-Match 'src/light.css' '--tzx-bg\s*:\s*#fcfcfc' 'blog light page background'
Assert-Match 'src/light.css' '--tzx-surface\s*:\s*rgba\(255,\s*255,\s*255,\s*0\.88\)' 'blog light content surface'
Assert-Match 'src/light.css' '--tzx-surface-raised\s*:\s*rgba\(255,\s*255,\s*255,\s*0\.88\)' 'blog light raised surface'
Assert-Match 'src/light.css' '--tzx-code-bg\s*:\s*#f4f5f8' 'blog light code surface'
Assert-Match 'src/light.css' '--tzx-code-text\s*:\s*#303545' 'blog light code text'
Assert-Match 'src/light.css' '--tzx-shadow\s*:\s*0\s+10px\s+30px\s+rgba\(15,\s*23,\s*42,\s*0\.08\)' 'blog light content shadow'
Assert-Match 'src/light.css' '--tzx-glass-border\s*:\s*color-mix\(in\s+srgb,\s*#5c6bc0\s+20%,\s*transparent\)' 'light source glass border'
Assert-Match 'src/dark.css' '--tzx-glass-border\s*:\s*rgba\(121,\s*134,\s*203,\s*0\.22\)' 'dark source glass border'
Assert-Match 'src/light.css' '--tzx-blockquote-surface\s*:\s*rgba\(255,\s*255,\s*255,\s*0\.58\)' 'light blockquote surface'
Assert-Match 'src/dark.css' '--tzx-blockquote-surface\s*:\s*rgba\(33,\s*37,\s*43,\s*0\.64\)' 'dark blockquote surface'
Assert-Match 'src/light.css' '--tzx-blockquote-gradient-one\s*:\s*radial-gradient\(circle\s+at\s+8%\s+0%,\s*rgba\(99,\s*102,\s*241,\s*0\.14\),\s*transparent\s+34%\)' 'light first blockquote gradient'
Assert-Match 'src/dark.css' '--tzx-blockquote-gradient-one\s*:\s*radial-gradient\(circle\s+at\s+8%\s+0%,\s*rgba\(99,\s*102,\s*241,\s*0\.17\),\s*transparent\s+34%\)' 'dark first blockquote gradient'
Assert-Match 'src/light.css' '--tzx-blockquote-gradient-three\s*:\s*radial-gradient\(circle\s+at\s+62%\s+110%,\s*rgba\(192,\s*132,\s*252,\s*0\.09\),\s*transparent\s+40%\)' 'light third blockquote gradient'
Assert-Match 'src/dark.css' '--tzx-blockquote-gradient-three\s*:\s*radial-gradient\(circle\s+at\s+62%\s+110%,\s*rgba\(192,\s*132,\s*252,\s*0\.09\),\s*transparent\s+40%\)' 'dark third blockquote gradient'
Assert-Match 'src/light.css' '--tzx-table-gradient-one\s*:\s*radial-gradient\(circle\s+at\s+5%\s+0%,\s*rgba\(99,\s*102,\s*241,\s*0\.12\),\s*transparent\s+34%\)' 'light first table gradient'
Assert-Match 'src/light.css' '--tzx-table-gradient-two\s*:\s*radial-gradient\(circle\s+at\s+95%\s+10%,\s*rgba\(56,\s*189,\s*248,\s*0\.09\),\s*transparent\s+38%\)' 'light second table gradient'
Assert-Match 'src/light.css' '--tzx-table-surface\s*:\s*rgba\(255,\s*255,\s*255,\s*0\.58\)' 'light table surface'
Assert-Match 'src/dark.css' '--tzx-table-gradient-one\s*:\s*radial-gradient\(circle\s+at\s+5%\s+0%,\s*rgba\(99,\s*102,\s*241,\s*0\.15\),\s*transparent\s+34%\)' 'dark first table gradient'
Assert-Match 'src/dark.css' '--tzx-table-gradient-two\s*:\s*radial-gradient\(circle\s+at\s+95%\s+10%,\s*rgba\(56,\s*189,\s*248,\s*0\.08\),\s*transparent\s+38%\)' 'dark second table gradient'
Assert-Match 'src/dark.css' '--tzx-table-surface\s*:\s*rgba\(33,\s*37,\s*43,\s*0\.66\)' 'dark table surface'
Assert-Match 'src/light.css' '--tzx-table-header-bg\s*:\s*rgba\(74,\s*84,\s*175,\s*0\.09\)' 'light table header background'
Assert-Match 'src/light.css' '--tzx-table-header-text\s*:\s*#4a54af' 'light table header text'
Assert-Match 'src/light.css' '--tzx-table-row-alt\s*:\s*rgba\(92,\s*107,\s*192,\s*0\.045\)' 'light table alternating row'
Assert-Match 'src/dark.css' '--tzx-table-header-bg\s*:\s*rgba\(74,\s*84,\s*175,\s*0\.24\)' 'dark table header background'
Assert-Match 'src/dark.css' '--tzx-table-header-text\s*:\s*#eef0ff' 'dark table header text'
Assert-Match 'src/dark.css' '--tzx-table-row-alt\s*:\s*rgba\(97,\s*113,\s*245,\s*0\.055\)' 'dark table alternating row'

Assert-NoBarePreCardRule 'src/base.css'
Assert-NoBareSelector 'src/base.css' '#write pre' 'Typora per-line code-block'
Assert-NoForbiddenTyporaCodeSelector 'src/base.css'
Assert-NoForbiddenCodeMirrorDeclaration 'src/base.css'
Assert-NoBareSelector 'src/base.css' '#write code' 'inline-code'
Assert-RuleMatch 'src/base.css' '^#write$' 'background\s*:\s*var\(--tzx-surface\)' 'article surface token relationship'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'font-family\s*:\s*var\(--tzx-code-font\)' 'Typora code font'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'overflow-x\s*:\s*auto' 'Typora code scrolling'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'border-radius\s*:\s*14px' '14px code radius'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'border\s*:\s*1px\s+solid\s+var\(--tzx-glass-border\)' 'source-intent code border'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'box-shadow\s*:\s*0\s+5px\s+16px\s+rgba\(15,\s*23,\s*42,\s*0\.06\)' 'source code shadow'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'background\s*:\s*var\(--tzx-code-bg\)' 'source code background token'
Assert-RuleMatch 'src/base.css' '^#write \.md-fences$' 'color\s*:\s*var\(--tzx-code-text\)' 'source code text token'
Assert-RuleMatch 'src/base.css' '^#write :not\(pre\) > code$' 'background\s*:\s*var\(--tzx-code-bg\)' 'inline code background'
Assert-RuleMatch 'src/base.css' '^#write :not\(pre\) > code$' 'color\s*:\s*var\(--tzx-code-text\)' 'inline code color'
Assert-RuleMatch 'src/base.css' '^#write blockquote$' 'border-left\s*:\s*4px\s+solid\s+var\(--tzx-nav-accent\)' 'navigation-accent blockquote edge'
Assert-RuleMatch 'src/base.css' '^#write blockquote$' 'border-radius\s*:\s*11px' '11px blockquote radius'
Assert-RuleMatch 'src/base.css' '^#write blockquote$' 'box-shadow\s*:\s*0\s+7px\s+22px\s+rgba\(63,\s*81,\s*181,\s*0\.07\)' 'source blockquote shadow'
Assert-RuleMatch 'src/base.css' '^#write blockquote$' 'var\(--tzx-blockquote-gradient-one\),\s*var\(--tzx-blockquote-gradient-two\),\s*var\(--tzx-blockquote-gradient-three\),\s*var\(--tzx-blockquote-surface\)' 'three-gradient palette-surface blockquote background'
Assert-RuleMatch 'src/base.css' '^#write table$' 'border-radius\s*:\s*10px' '10px table radius'
Assert-RuleMatch 'src/base.css' '^#write table$' 'font-size\s*:\s*0\.92rem' 'readable table text size'
Assert-RuleMatch 'src/base.css' '^#write table$' 'display\s*:\s*table' 'native screen table layout'
Assert-RuleMatch 'src/base.css' '^#write table$' '(?:^|[;\r\n])\s*width\s*:\s*100%' 'full-width native table'
Assert-RuleMatch 'src/base.css' '^#write table$' 'table-layout\s*:\s*auto' 'content-aware table track sizing'
Assert-RuleNoMatch 'src/base.css' '^#write table$' 'display\s*:\s*block' 'screen table block layout'
Assert-RuleNoMatch 'src/base.css' '^#write table$' 'overflow(?:-x)?\s*:\s*auto' 'screen table self-scrolling'
Assert-RuleMatch 'src/base.css' '^#write table$' 'var\(--tzx-table-gradient-one\),\s*var\(--tzx-table-gradient-two\),\s*var\(--tzx-table-surface\)' 'source table gradient background'
Assert-RuleMatch 'src/base.css' '^#write table$' 'box-shadow\s*:\s*0\s+7px\s+22px\s+rgba\(63,\s*81,\s*181,\s*0\.07\)' 'source table shadow'
Assert-RuleMatch 'src/base.css' '^#write th,\s*#write td$' 'padding\s*:\s*0\.72rem\s+0\.85rem' 'source table cell padding'
Assert-RuleMatch 'src/base.css' '^#write th,\s*#write td$' 'min-width\s*:\s*0' 'screen table cell minimum width reset'
Assert-RuleMatch 'src/base.css' '^#write th,\s*#write td$' 'overflow-wrap\s*:\s*anywhere' 'screen table cell wrapping'
Assert-RuleNoMatch 'src/base.css' '^#write th,\s*#write td$' 'min-width\s*:\s*7em' 'screen table cell fixed minimum width'
Assert-RuleMatch 'src/base.css' '^#write th$' 'background\s*:\s*var\(--tzx-table-header-bg\)' 'table header background token'
Assert-RuleMatch 'src/base.css' '^#write th$' 'color\s*:\s*var\(--tzx-table-header-text\)' 'table header text token'
Assert-RuleMatch 'src/base.css' '^#write tbody tr:nth-child\(even\)$' 'background\s*:\s*var\(--tzx-table-row-alt\)' 'alternating table rows'
Assert-RuleMatch 'src/base.css' '^#write tr:last-child td$' 'border-bottom\s*:\s*0' 'borderless final table row'

foreach ($selector in @('#write h1', '#write h2', '#write h3', '#write blockquote', '#write table', '#write :not(pre) > code', '#write .md-fences', '#write img', '.task-list-item', '.footnotes', '.md-toc', '.md-math-block')) {
    Assert-Match 'src/base.css' ([regex]::Escape($selector)) "$selector selector"
}
Assert-Match 'src/base.css' 'overflow-x\s*:\s*auto' 'horizontal overflow handling'

foreach ($selector in @('#typora-sidebar', '.file-tree-node', '.outline-item', '.sidebar-tabs', '#file-library-search-input', '.on-focus-mode', '#typora-source .cm-s-typora-default', '.cm-s-inner', '.ty-on-typewriter-mode')) {
    Assert-Match 'src/base.css' ([regex]::Escape($selector)) "$selector selector"
}
Assert-NoMatch 'src/base.css' '(?<![a-z-])\.focus-mode\b' 'non-native focus-mode selector'
Assert-NoMatch 'src/base.css' '(?<![a-z-])\.source-mode\b' 'non-native source-mode selector'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode \.md-end-block:not\(\.md-focus\):not\(\.md-focus-container\)$' 'opacity\s*:\s*0\.38' 'native unfocused end-block treatment'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode \.task-list-item:not\(\.md-focus-container\)\s*>\s*input$' 'opacity\s*:\s*0\.38' 'native unfocused task checkbox treatment'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode li\[cid\]:not\(\.md-focus-container\)$' 'color\s*:\s*var\(--tzx-text-muted\)' 'native unfocused list treatment'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode \.md-fences\.md-focus \.CodeMirror-code\s*>\s*\*:not\(\.CodeMirror-activeline\) \*$' 'color\s*:\s*var\(--tzx-text-muted\)' 'native unfocused fence line treatment'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode \.CodeMirror\.cm-s-inner:not\(\.CodeMirror-focused\) \*$' 'color\s*:\s*var\(--tzx-text-muted\)' 'native unfocused fence treatment'
Assert-RuleMatch 'src/base.css' '^\.on-focus-mode #typora-source \.CodeMirror-code\s*>\s*\*:not\(\.CodeMirror-activeline\) \*$' 'color\s*:\s*var\(--tzx-text-muted\)' 'native unfocused source line treatment'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default$' 'font-family\s*:\s*var\(--tzx-code-font\)' 'source-mode native font'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default$' 'background\s*:\s*var\(--tzx-bg\)' 'source-mode native background'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default$' 'color\s*:\s*var\(--tzx-code-text\)' 'source-mode native foreground'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default \.CodeMirror-selected$' 'background\s*:\s*var\(--tzx-selection\)' 'source-mode selection color'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default \.CodeMirror-activeline-background$' 'background\s*:\s*color-mix\(' 'source-mode active-line color'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default \.CodeMirror-gutters$' 'background\s*:\s*var\(--tzx-bg\)' 'source-mode gutter background'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default \.CodeMirror-gutters$' 'color\s*:\s*var\(--tzx-text-muted\)' 'source-mode gutter foreground'
Assert-RuleMatch 'src/base.css' '^#typora-source \.cm-s-typora-default \.CodeMirror-cursor$' 'border-left-color\s*:\s*var\(--tzx-primary\)' 'source-mode visible cursor'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner$' 'font-family\s*:\s*var\(--tzx-code-font\)' 'fence CodeMirror font'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner$' 'background\s*:\s*var\(--tzx-code-bg\)' 'fence CodeMirror background color'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner$' 'color\s*:\s*var\(--tzx-code-text\)' 'fence CodeMirror foreground color'
foreach ($themeFile in @('src/light.css', 'src/dark.css')) {
    foreach ($token in @('plain', 'keyword', 'definition', 'string', 'comment', 'number', 'builtin', 'meta')) {
        Assert-Match $themeFile ("--tzx-syntax-$token\s*:") "$token syntax token"
    }
}
Assert-Match 'src/dark.css' '--mermaid-theme\s*:\s*night' 'Mermaid night renderer theme'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-variable,\s*#write \.cm-s-inner \.cm-operator,\s*#write \.cm-s-inner \.cm-property,\s*#write \.cm-s-inner \.cm-bracket$' 'color\s*:\s*var\(--tzx-syntax-plain\)' 'fence plain token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-keyword,\s*#write \.cm-s-inner \.cm-tag,\s*#write \.cm-s-inner \.cm-attribute$' 'color\s*:\s*var\(--tzx-syntax-keyword\)' 'fence keyword token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-def,\s*#write \.cm-s-inner \.cm-header,\s*#write \.cm-s-inner \.cm-variable-2,\s*#write \.cm-s-inner \.cm-variable-3$' 'color\s*:\s*var\(--tzx-syntax-definition\)' 'fence definition token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-string,\s*#write \.cm-s-inner \.cm-string-2$' 'color\s*:\s*var\(--tzx-syntax-string\)' 'fence string token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-comment$' 'color\s*:\s*var\(--tzx-syntax-comment\)' 'fence comment token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-number,\s*#write \.cm-s-inner \.cm-atom$' 'color\s*:\s*var\(--tzx-syntax-number\)' 'fence number token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-builtin$' 'color\s*:\s*var\(--tzx-syntax-builtin\)' 'fence builtin token foreground'
Assert-RuleMatch 'src/base.css' '^#write \.cm-s-inner \.cm-meta,\s*#write \.cm-s-inner \.cm-qualifier$' 'color\s*:\s*var\(--tzx-syntax-meta\)' 'fence meta token foreground'
Assert-Match 'src/base.css' '@media\s*\(max-width:\s*720px\)' 'narrow-window media query'
Assert-Match 'src/base.css' '@media\s+print' 'print media query'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write .md-fences' 'box-shadow\s*:\s*none\s*!important' 'print code shadow removal'
Assert-MediaNoBareSelector 'src/base.css' '^@media\s+print$' '#write pre' 'per-line code printing'
Assert-MediaNoPaletteDeclarations 'src/base.css' '^@media\s+print$'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write img' 'box-shadow\s*:\s*none\s*!important' 'print image shadow removal'
foreach ($selector in @('#write h1', '#write h2', '#write h3', '#write h4', '#write h5', '#write h6')) {
    Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' $selector 'break-after\s*:\s*avoid-page' "$selector print pagination"
}

# Screen and print table contracts are intentionally scoped separately. Both
# preserve table layout; screen uses auto tracks and print uses fixed tracks.
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write table' 'width\s*:\s*100%\s*!important' 'print table page width'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write table' 'min-width\s*:\s*0\s*!important' 'print table minimum width reset'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write table' 'overflow\s*:\s*visible\s*!important' 'print table visible overflow'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write table' 'table-layout\s*:\s*fixed' 'print table page-safe layout'
foreach ($selector in @('#write th', '#write td')) {
    Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' $selector 'min-width\s*:\s*0\s*!important' "$selector print minimum width reset"
    Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' $selector 'white-space\s*:\s*normal\s*!important' "$selector print wrapping"
    Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' $selector 'overflow-wrap\s*:\s*anywhere' "$selector print long-token wrapping"
    Assert-MediaRuleNoMatch 'src/base.css' '^@media\s+print$' $selector 'min-width\s*:\s*7em' "$selector screen cell minimum width"
}
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '.on-focus-mode #write .md-end-block:not(.md-focus):not(.md-focus-container)' 'opacity\s*:\s*1' 'print focused-document block opacity reset'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '.on-focus-mode #write .task-list-item:not(.md-focus-container) > input' 'opacity\s*:\s*1' 'print focused-document task opacity reset'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#write img' 'max-width\s*:\s*100%\s*!important' 'print image page width'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '#typora-sidebar' 'display\s*:\s*none\s*!important' 'print sidebar hiding'
Assert-MediaRuleMatch 'src/base.css' '^@media\s+print$' '.sidebar-footer' 'display\s*:\s*none\s*!important' 'print sidebar footer hiding'

$typoraCodeSelectorCounterexamples = @(
    @{ Label = 'CodeMirror pre line'; Css = '#write pre.CodeMirror-line { padding: 1em; }' },
    @{ Label = 'CodeMirror line'; Css = '#write .CodeMirror-line { padding: 1em; }' },
    @{ Label = 'direct pre descendant'; Css = '#write pre code { color: red; }' },
    @{ Label = 'fences pre descendant'; Css = '#write .md-fences pre { background: red; }' },
    @{ Label = 'CodeMirror pre descendant'; Css = '#write .CodeMirror-code > pre { overflow-x: auto; }' }
)
foreach ($counterexample in $typoraCodeSelectorCounterexamples) {
    if (-not (Test-HasForbiddenTyporaCodeSelector $counterexample.Css)) {
        $failures.Add("Typora code-line guard failed $($counterexample.Label) counterexample")
    }
}
if (Test-HasForbiddenTyporaCodeSelector '#write pre.md-meta-block { padding: 1em; }') {
    $failures.Add('Typora code-line guard rejected the allowed md-meta pre selector')
}
foreach ($counterexample in @(
    @{ Label = 'CodeMirror line radius'; Css = '.CodeMirror-line { border-radius: 4px; }' },
    @{ Label = 'CodeMirror widget padding'; Css = '.cm-s-inner .CodeMirror-code { padding: 1em; }' },
    @{ Label = 'CodeMirror shadow'; Css = '#typora-source .cm-s-typora-default { box-shadow: none; }' },
    @{ Label = 'inner direct line background'; Css = '.cm-s-inner .CodeMirror-code > * { background: red; }' },
    @{ Label = 'source direct line background'; Css = '.cm-s-typora-default .CodeMirror-code > * { background-color: red; }' },
    @{ Label = 'CodeMirror div line background'; Css = '.CodeMirror-code > div { background: red; }' },
    @{ Label = 'CodeMirror pre line background'; Css = '.CodeMirror-code > pre { background: red; }' },
    @{ Label = 'CodeMirror wildcard line background'; Css = '.CodeMirror-code > * { background: red; }' },
    @{ Label = 'CodeMirror positioned line'; Css = '.CodeMirror-code > * { position: relative; }' },
    @{ Label = 'CodeMirror overflowing line'; Css = '.CodeMirror-code > * { overflow: auto; }' }
)) {
    if (-not (Test-HasForbiddenCodeMirrorDeclaration $counterexample.Css)) {
        $failures.Add("CodeMirror declaration guard failed $($counterexample.Label) counterexample")
    }
}
if (Test-HasForbiddenCodeMirrorDeclaration '.CodeMirror-line { color: #222; font-family: monospace; }') {
    $failures.Add('CodeMirror declaration guard rejected allowed line color/font declarations')
}
foreach ($allowedExample in @(
    '.cm-s-typora-default .CodeMirror-activeline-background { background: #eee; }',
    '.cm-s-typora-default .CodeMirror-selected { background: #ddd; }'
)) {
    if (Test-HasForbiddenCodeMirrorDeclaration $allowedExample) {
        $failures.Add("CodeMirror declaration guard rejected allowed state styling: $allowedExample")
    }
}
foreach ($selector in @('.file-tree-node:focus-visible', '.file-node-content:focus-visible', '.outline-item:focus-visible', '.sidebar-tabs :focus-visible')) {
    Assert-Match 'src/base.css' ([regex]::Escape($selector)) "$selector focus-visible selector"
}
Assert-NoBareSelector 'src/base.css' '#file-library-search-input:focus-visible' 'double-ring search input focus-visible'
Assert-Match 'src/base.css' 'outline\s*:\s*2px\s+solid\s+var\(--tzx-nav-accent\)' 'navigation focus outline'
Assert-Match 'src/base.css' 'outline-offset\s*:\s*2px' 'navigation focus outline offset'
Assert-Match 'src/base.css' ([regex]::Escape('.file-node-content.active::before')) 'file content active marker'
Assert-Match 'src/base.css' 'translateX\(4px\)' 'sidebar hover translation'
Assert-Match 'src/base.css' '@media\s*\(prefers-reduced-motion:\s*reduce\)' 'reduced motion media query'
Assert-Match 'src/base.css' 'background\s*:\s*var\(--tzx-nav-hover\)' 'navigation hover token usage'
Assert-Match 'src/base.css' 'border-radius\s*:\s*6px' 'navigation item radius'
Assert-Match 'src/base.css' '(?s)@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{.*?transition\s*:\s*none;.*?transform\s*:\s*none;' 'reduced motion transition and transform overrides'
Assert-Match 'src/base.css' '(?s)\.sidebar-tabs\s+\.active\s*\{\s*color\s*:\s*var\(--tzx-nav-accent\)' 'active sidebar tab navigation foreground'
Assert-Match 'src/base.css' '(?s)\.file-tree-node\.active,\s*\.file-node-content\.active,\s*\.outline-item-active\s*\{[^}]*;\s*color\s*:\s*var\(--tzx-nav-accent\)' 'active tree and outline navigation foreground'

# Windows Typora outline DOM: wrapper > item > label. Normalize every label
# and its inline content while keeping hierarchy in wrapper-level indentation.
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'font-size\s*:\s*13px' 'sidebar-scale outline label'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'line-height\s*:\s*1\.45' 'consistent outline label line height'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'overflow\s*:\s*hidden' 'outline label overflow clipping'
Assert-RuleNoMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'max-width\s*:\s*0(?:\D|$)' 'zero-width outline label collapse'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'text-overflow\s*:\s*ellipsis' 'outline label ellipsis'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label$' 'white-space\s*:\s*nowrap' 'single-line outline label'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-label \*$' 'font-size\s*:\s*inherit' 'normalized outline inline descendants'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-item-wrapper\.outline-h1 > \.outline-item > \.outline-label$' 'font-size\s*:\s*13px' 'normalized first outline H1'
Assert-RuleMatch 'src/base.css' '^\.pin-outline #outline-content \.outline-active strong$' 'font-weight\s*:\s*500' 'restrained current heading emphasis'
foreach ($level in 2..6) {
    Assert-RuleNoMatch 'src/base.css' ("^#typora-sidebar #outline-content \.outline-item-wrapper\.outline-h$level > \.outline-item$") 'padding-left\s*:' "custom outline H$level indentation override"
}
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-item-active$' 'background\s*:\s*var\(--tzx-nav-hover\)' 'single active outline row background'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-item-active$' 'color\s*:\s*var\(--tzx-nav-accent\)' 'readable active outline foreground'
Assert-RuleNoMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-active(?:,|$)' 'background\s*:' 'overlapping active outline label background'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #outline-content \.outline-h1 > \.outline-item\.outline-item-active$' 'padding-left\s*:\s*8px' 'active H1 marker clearance'

# Windows Typora search DOM: search panel contains the input and actual close
# button. Input focus uses one border treatment; the close button owns its ring.
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel$' 'padding\s*:\s*8px\s+10px' 'search panel spacing'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel$' 'gap\s*:\s*6px' 'search panel control gap'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input$' 'height\s*:\s*32px' 'search input height'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input$' 'padding\s*:\s*0\s+10px' 'search input padding'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input$' 'border-radius\s*:\s*7px' 'search input radius'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input:focus$' 'border-color\s*:\s*var\(--tzx-nav-accent\)' 'single search input focus border'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input:focus$' 'outline\s*:\s*none' 'search input focus outline removal'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #file-library-search-input:focus$' 'box-shadow\s*:\s*none' 'search input focus shadow removal'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'width\s*:\s*28px' 'compact outline filter close button width'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'height\s*:\s*28px' 'compact outline filter close button height'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'color\s*:\s*var\(--tzx-text-muted\)' 'muted outline filter close button'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'position\s*:\s*static' 'outline filter close flex positioning reset'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'right\s*:\s*auto' 'outline filter close right offset reset'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn$' 'opacity\s*:\s*1' 'outline filter close opacity reset'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn:hover$' 'background\s*:\s*var\(--tzx-nav-hover\)' 'outline filter close hover background'
Assert-RuleMatch 'src/base.css' '^#typora-sidebar #file-library-search-panel #close-outline-filter-btn:focus-visible$' 'outline\s*:\s*2px\s+solid\s+var\(--tzx-nav-accent\)' 'outline filter close focus ring'
$baseCss = Get-Content -LiteralPath (Join-Path $projectRoot 'src/base.css') -Raw
if ($baseCss -match '(?s)\.file-tree-node:hover[^\{]*\{[^}]*\btransform\s*:(?!\s*none\b)') {
    $failures.Add('src/base.css lets file-tree-node hover transform')
}

${showcase} = Get-ShowcaseMarkdown 'showcase.md'
if ($null -ne ${showcase}) {
    foreach ($language in @('cpp', 'text', 'mermaid')) {
        if (${showcase}.FenceCounts[$language] -ne 1) {
            $failures.Add("showcase.md requires exactly one closed ```$language fence")
        }
    }

    Assert-ShowcaseMatch ${showcase}.Content '(?s)\A---\n.*?\n---\n' 'frontmatter beginning on the first line with a closing delimiter'
    $body = ${showcase}.Outside -replace '(?s)\A---\n.*?\n---\n?', ''
    foreach ($level in 1..6) {
        Assert-ShowcaseMatch $body ("(?m)^" + ('#' * $level) + ' ') "outside-fence H$level heading"
    }
    Assert-ShowcaseMatch $body '(?m)^> ' 'outside-fence blockquote'
    Assert-ShowcaseMatch $body '(?m)^\[toc\]\s*$' 'outside-fence TOC'
    Assert-ShowcaseMatch $body '(?m)^- \[ \] ' 'outside-fence unchecked task item'
    Assert-ShowcaseMatch $body '(?m)^- \[x\] ' 'outside-fence checked task item'
    Assert-ShowcaseMatch $body '(?m)^\|[^\n]+\|\n\|(?:\s*:?-{3,}:?\s*\|)+\s*$' 'table header followed by separator'
    if ([regex]::Matches($body, '(?m)^\$\$\s*$').Count -ne 2) {
        $failures.Add('showcase.md requires one paired outside-fence display-math delimiter set')
    }
    Assert-ShowcaseMatch $body '(?m)\[\^1\](?!:)' 'outside-fence footnote reference'
    Assert-ShowcaseMatch $body '(?m)^\[\^1\]:\s+' 'outside-fence footnote definition'
    Assert-ShowcaseMatch $body '(?m)^---\s*$' 'outside-fence horizontal rule'
    Assert-ShowcaseMatch $body '\$E\s*=\s*mc\^2\$' 'inline math'
    if ($body -match '!\[[^\]]*\]\(') {
        $failures.Add('showcase.md must not depend on image resources')
    }
}

$fencedOnlyCounterexample = @'
```text
---
# hidden heading
[toc]
> hidden quote
- [ ] hidden task
| Header | Value |
| --- | ---: |
$$
math
$$
[^1] and [^1]: hidden definition
---
```cpp
```mermaid
```
'@ -replace "`r`n", "`n"
$legacyPatterns = @('(?m)^---$', '(?m)^# ', '(?m)^> ', '(?m)^\|.+\|$', '```cpp', '```mermaid', '\$\$', '(?m)^\[toc\]$', '\[\^1\]', '- \[ \]')
if (-not (@($legacyPatterns | Where-Object { $fencedOnlyCounterexample -notmatch $_ }).Count -eq 0)) {
    $failures.Add('fenced-only counterexample no longer represents the legacy token-only strategy')
}
$fencedOnlyAnalysis = Get-OutsideFencedMarkdown $fencedOnlyCounterexample
if ($null -ne $fencedOnlyAnalysis -and $fencedOnlyAnalysis.Outside -match '(?m)^# ') {
    $failures.Add('fenced-code stripping failed to reject the fenced-only counterexample')
}

$readmeChinesePhrases = @(
    (([char[]](0x4e3b, 0x9898, 0x7279, 0x70b9)) -join ''),
    (([char[]](0x6548, 0x679c, 0x5c55, 0x793a)) -join ''),
    (([char[]](0x63a8, 0x8350, 0x5b57, 0x4f53)) -join ''),
    (([char[]](0x5b89, 0x88c5)) -join ''),
    (([char[]](0x66f4, 0x65b0)) -join ''),
    (([char[]](0x5378, 0x8f7d)) -join ''),
    (([char[]](0x5f00, 0x53d1, 0x4e0e, 0x9a8c, 0x8bc1)) -join ''),
    (([char[]](0x5e38, 0x89c1, 0x95ee, 0x9898)) -join '')
)
foreach ($phrase in $readmeChinesePhrases) {
    Assert-Match 'README.md' ([regex]::Escape($phrase)) "Chinese README phrase $phrase"
}
foreach ($phrase in @('Noto Serif SC', 'Maple Mono CN', 'tangentzx-light.css', 'tangentzx-dark.css', 'showcase.md', 'screenshots/light.png', 'screenshots/dark.png')) {
    Assert-Match 'README.md' ([regex]::Escape($phrase)) "README public phrase $phrase"
}
Assert-Match 'README.md' 'https://github\.com/notofonts/noto-cjk/releases' 'official Noto release URL'
Assert-Match 'README.md' 'https://github\.com/subframe7536/maple-font/releases' 'official Maple Mono release URL'
Assert-Match 'README.md' '(?s)<!--.*?!\[[^\]]+\]\(screenshots/light\.png\).*?-->' 'commented light screenshot snippet'
Assert-Match 'README.md' '(?s)<!--.*?!\[[^\]]+\]\(screenshots/dark\.png\).*?-->' 'commented dark screenshot snippet'
$readmeText = (Get-Content -LiteralPath (Join-Path $projectRoot 'README.md') -Raw -Encoding UTF8) -replace "`r`n", "`n"
$readmeWithoutComments = $readmeText -replace '(?s)<!--.*?-->', ''
if ($readmeWithoutComments -match '!\[[^\]]+\]\(screenshots/(?:light|dark)\.png\)') {
    $failures.Add('README.md exposes a visible screenshot link before the PNG exists')
}
$onlyNeedPhrase = ([char[]](0x53ea, 0x9700)) -join ''
Assert-Match 'README.md' (('(?s)' + [regex]::Escape($onlyNeedPhrase) + '.{0,80}`tangentzx-(?:light|dark)\.css`')) 'one-file installation statement'
foreach ($path in @('screenshots/light.png', 'screenshots/dark.png')) {
    Assert-Match 'screenshots/README.md' ([regex]::Escape($path)) "screenshot target $path"
}

foreach ($counterexample in @('@import "//cdn.example/theme.css";', '.icon { background: url("//cdn.example/icon.svg"); }')) {
    if ($counterexample -notmatch $remoteCssResourcePattern) {
        $failures.Add("remote resource guard failed protocol-relative counterexample: $counterexample")
    }
}

$failedGitInspection = Get-GitTrackedFiles (Join-Path $projectRoot '__missing_git_repository__') '*.js'
if ($failedGitInspection.Succeeded) {
    $failures.Add('Git inspection guard accepted a missing repository counterexample')
}

$trackedJavaScript = Get-GitTrackedFiles $projectRoot '*.js'
if (-not $trackedJavaScript.Succeeded) {
    $failures.Add('Unable to inspect tracked JavaScript files')
} elseif ($trackedJavaScript.Files.Count -gt 0) {
    $failures.Add("Deliverable contains tracked JavaScript: $($trackedJavaScript.Files -join ', ')")
}
$deliverableJavaScript = @(Get-ChildItem -LiteralPath $projectRoot -Recurse -File -Filter '*.js' | Where-Object {
    $_.FullName -notmatch '[\\/](?:\.git|\.superpowers|docs)[\\/]'
})
if ($deliverableJavaScript.Count -gt 0) {
    $failures.Add("Deliverable paths contain JavaScript: $($deliverableJavaScript.FullName -join ', ')")
}

$trackedSddReports = Get-GitTrackedFiles $projectRoot '.superpowers/sdd/*-report.md'
if (-not $trackedSddReports.Succeeded) {
    $failures.Add('Unable to inspect tracked SDD reports')
} elseif ($trackedSddReports.Files.Count -gt 0) {
    $failures.Add("Deliverable tracks internal SDD reports: $($trackedSddReports.Files -join ', ')")
}

foreach ($entry in @('src/light.css', 'src/dark.css', 'src/base.css')) {
    $themeCss = Get-Content -LiteralPath (Join-Path $projectRoot $entry) -Raw
    if (Test-FixedRightSidebarRule $themeCss) {
        $failures.Add("$entry contains a fixed right-hand navigation sidebar")
    }
}

$fixedRightSidebarCounterexamples = @(
    @{ Label = 'right-before-position'; Css = '.outline-flyout { right: 0; position: fixed; }'; Expected = $true },
    @{ Label = 'logical-inset'; Css = '.sidebar-flyout { position: fixed; inset-inline-end: 0; }'; Expected = $true },
    @{ Label = 'file-library panel'; Css = '.file-library-panel { position: fixed; right: 0; }'; Expected = $true },
    @{ Label = 'unrelated-fixed-ui'; Css = '.toast { position: fixed; right: 0; }'; Expected = $false }
)
foreach ($counterexample in $fixedRightSidebarCounterexamples) {
    if ((Test-FixedRightSidebarRule $counterexample.Css) -ne $counterexample.Expected) {
        $failures.Add("fixed-right navigation guard failed $($counterexample.Label)")
    }
}

foreach ($releaseFile in @('tangentzx-light.css', 'tangentzx-dark.css')) {
    Assert-CanonicalUtf8 $releaseFile
    Assert-NoMatch $releaseFile '(?im)^\s*@import\b' 'CSS import in standalone release'
    Assert-NoMatch $releaseFile '(?i)(?:https?:)?//' 'remote CSS dependency in standalone release'
}

Assert-DeterministicBuilder

$expectedLight = Get-ExpectedStandaloneTheme 'src/light.css'
$expectedDark = Get-ExpectedStandaloneTheme 'src/dark.css'
$actualLight = Get-NormalizedText 'tangentzx-light.css'
$actualDark = Get-NormalizedText 'tangentzx-dark.css'
if ($actualLight -cne $expectedLight) {
    $failures.Add('tangentzx-light.css is not the deterministic standalone build output')
}
if ($actualDark -cne $expectedDark) {
    $failures.Add('tangentzx-dark.css is not the deterministic standalone build output')
}

foreach ($releaseFile in @('tangentzx-light.css', 'tangentzx-dark.css')) {
    foreach ($representativeSelector in @(
        '#write {',
        '#write table',
        '#typora-sidebar',
        '#write .cm-s-inner',
        '#write .md-diagram-panel',
        '@media (max-width: 720px)',
        '@media print'
    )) {
        Assert-Match $releaseFile ([regex]::Escape($representativeSelector)) "$representativeSelector standalone rule"
    }
}

if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Error $_ -ErrorAction Continue }
    exit 1
}

Write-Output 'Theme contract passed.'
