$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$header = "/* Generated by scripts/build.ps1. Edit src/*.css, then rebuild. */`n`n"

function Get-NormalizedSource([string]$relativePath) {
    $path = Join-Path $projectRoot $relativePath
    $text = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    return ($text -replace "`r`n", "`n").TrimEnd() + "`n"
}

$base = Get-NormalizedSource 'src/base.css'
foreach ($variant in @('light', 'dark')) {
    $palette = Get-NormalizedSource "src/$variant.css"
    $output = $header + $palette + "`n" + $base
    $outputPath = Join-Path $projectRoot "tangentzx-$variant.css"
    [System.IO.File]::WriteAllText($outputPath, $output, $utf8NoBom)
}
